### PR TITLE
Pangolin2 `6005` runtime upgrade

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Review by boundless-forest — APPROVED** [review]

**Comment by boundless-forest** [comment]
It's a good change to test if the try-runtime works well.

**Comment by AurevoirXavier** [comment]
> It's a good change to test if the try-runtime works well.

Is there any try runtime code?

`pallet-assets`?

**Comment by boundless-forest** [comment]
> > It's a good change to test if the try-runtime works well.
> 
> Is there any try runtime code?
> 
> `pallet-assets`?

Yes. There is a migration section under the Panglin runtime. The on-chain runtime version is 6001.

**Comment by AurevoirXavier** [comment]
> Yes. There is a migration section under the Panglin runtime. The on-chain runtime version is 6001.

But there isn't any try time code.

https://github.com/darwinia-network/darwinia-2.0/blob/e6c048c1f52ea47248f99bc6f4956571ad1cea84/runtime/pangolin/src/migration.rs#L10

**Comment by boundless-forest** [comment]
> > Yes. There is a migration section under the Panglin runtime. The on-chain runtime version is 6001.
> 
> But there isn't any try time code.
> 
> https://github.com/darwinia-network/darwinia-2.0/blob/e6c048c1f52ea47248f99bc6f4956571ad1cea84/runtime/pangolin/src/migration.rs#L10

Perhaps the expression is not clear before.  I mean the `try-runtime` test. When you run the `try-runtime` test, it will apply the migration script based on the on-chain runtime state. right?

**Comment by AurevoirXavier** [comment]
But there isn't any assertion. I can't know the try-runtime result. I can only know this get panic.

**Pull request merged**
