### PR TITLE
`account-migration` runtime tests

### PR DESCRIPTION
**Pull request by boundless-forest**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Actually, these are pallet unit tests. I think testing on Pangolin is enough.

**Comment by boundless-forest** [comment]
> Actually, these are pallet unit tests. I think testing on Pangolin is enough?

To be honest, most of the tests and runtime configurations are identical across runtimes.  I still prefer to add them to each runtime to ensure the functionality works for all the runtimes. We might have some dedicated tests in a specific runtime in the future.

**Comment by AurevoirXavier** [comment]
But the code is completely the same. If I want to update the tests, I need to update a lot of files.

I think we can add a test macro under the account-migration. Then use it in the runtimes.

**Comment by boundless-forest** [comment]
> If I want to update the tests, I need to update many files. And we might miss something in the future.

Only 3 files, it much similar to the runtime config. If you want to update some very command config in pallet, you need to tweak 3 places in our case.

> I think we can add a test macro under the account-migration. Then use it in the runtimes.

The runtime integrates test reply on the pallet test macro, which looks weird. This increase the tests maintain difficulty, it's hard to pick up which part moves to the macros. Compared to moving the whole `account-migration.rs` to the macro in pallet, moving it to a common file in the runtime would be a better solution in my mind.

Or should we move the account-migration tests in this pr to the pallet level instead of the runtime level? Those test cases are more like pallet unit tests.

**Comment by AurevoirXavier** [comment]
Something like this:
https://github.com/darwinia-network/darwinia-common/blob/6a9392cfb9fe2c99b1c2b47d0c36125d61991bb7/node/runtime/common/src/impls.rs#L107-L204

**Comment by boundless-forest** [comment]
> Something like this would be helpful. https://github.com/darwinia-network/darwinia-common/blob/6a9392cfb9fe2c99b1c2b47d0c36125d61991bb7/node/runtime/common/src/impls.rs#L107-L204

This local in the runtime common folder instead of the pallet.  I think the idle test flow would be like `Unit test(must have) + integrate test(Optional)`, the current practice here seems like no unit tests and treat unit tests as integrate tests.

**Pull request merged**
